# spring:
#   application:
#     name: Config-Defult

eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defualt: http://localhost:8761/euraka
